--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (6bc9ef8)
-- Dumped by pg_dump version 17.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO neondb_owner;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO neondb_owner;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO neondb_owner;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO neondb_owner;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO neondb_owner;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO neondb_owner;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO neondb_owner;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO neondb_owner;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO neondb_owner;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO neondb_owner;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO neondb_owner;

--
-- Name: tienda_brand; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.tienda_brand (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    logo character varying(100) NOT NULL
);


ALTER TABLE public.tienda_brand OWNER TO neondb_owner;

--
-- Name: tienda_brand_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.tienda_brand ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_brand_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda_categoriaimagen; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.tienda_categoriaimagen (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    "order" integer NOT NULL,
    category_id bigint NOT NULL,
    CONSTRAINT tienda_categoriaimagen_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.tienda_categoriaimagen OWNER TO neondb_owner;

--
-- Name: tienda_categoriaimagen_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.tienda_categoriaimagen ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_categoriaimagen_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda_category; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.tienda_category (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    description text NOT NULL,
    image character varying(100)
);


ALTER TABLE public.tienda_category OWNER TO neondb_owner;

--
-- Name: tienda_category_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.tienda_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda_product; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.tienda_product (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    origin character varying(3) NOT NULL,
    original_price numeric(8,2) NOT NULL,
    discount integer NOT NULL,
    price numeric(8,2) NOT NULL,
    stock integer NOT NULL,
    featured boolean NOT NULL,
    category_deal boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    brand_id bigint,
    category_id bigint,
    CONSTRAINT tienda_product_discount_check CHECK ((discount >= 0)),
    CONSTRAINT tienda_product_stock_check CHECK ((stock >= 0))
);


ALTER TABLE public.tienda_product OWNER TO neondb_owner;

--
-- Name: tienda_product_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.tienda_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda_productimage; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.tienda_productimage (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    "order" integer NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT tienda_productimage_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.tienda_productimage OWNER TO neondb_owner;

--
-- Name: tienda_productimage_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.tienda_productimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_productimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda_servicio; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.tienda_servicio (
    id bigint NOT NULL,
    "nombreServicio" character varying(200) NOT NULL,
    "precioOriginal" numeric(10,2) NOT NULL,
    descuento integer NOT NULL,
    precio numeric(10,2) NOT NULL,
    descripcion text NOT NULL,
    caracteristicas jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT tienda_servicio_descuento_check CHECK ((descuento >= 0))
);


ALTER TABLE public.tienda_servicio OWNER TO neondb_owner;

--
-- Name: tienda_servicio_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.tienda_servicio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_servicio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda_servicioimagen; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.tienda_servicioimagen (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    "order" integer NOT NULL,
    service_id bigint NOT NULL,
    CONSTRAINT tienda_servicioimagen_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.tienda_servicioimagen OWNER TO neondb_owner;

--
-- Name: tienda_servicioimagen_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.tienda_servicioimagen ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_servicioimagen_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add Token	7	add_token
26	Can change Token	7	change_token
27	Can delete Token	7	delete_token
28	Can view Token	7	view_token
29	Can add Token	8	add_tokenproxy
30	Can change Token	8	change_tokenproxy
31	Can delete Token	8	delete_tokenproxy
32	Can view Token	8	view_tokenproxy
33	Can add Brand	9	add_brand
34	Can change Brand	9	change_brand
35	Can delete Brand	9	delete_brand
36	Can view Brand	9	view_brand
37	Can add category	10	add_category
38	Can change category	10	change_category
39	Can delete category	10	delete_category
40	Can view category	10	view_category
41	Can add Servicio	11	add_servicio
42	Can change Servicio	11	change_servicio
43	Can delete Servicio	11	delete_servicio
44	Can view Servicio	11	view_servicio
45	Can add Category image	12	add_categoriaimagen
46	Can change Category image	12	change_categoriaimagen
47	Can delete Category image	12	delete_categoriaimagen
48	Can view Category image	12	view_categoriaimagen
49	Can add Product	13	add_product
50	Can change Product	13	change_product
51	Can delete Product	13	delete_product
52	Can view Product	13	view_product
53	Can add Product image	14	add_productimage
54	Can change Product image	14	change_productimage
55	Can delete Product image	14	delete_productimage
56	Can view Product image	14	view_productimage
57	Can add Servicio image	15	add_servicioimagen
58	Can change Servicio image	15	change_servicioimagen
59	Can delete Servicio image	15	delete_servicioimagen
60	Can view Servicio image	15	view_servicioimagen
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$C9zu7BrlpGcICbhdd9c6lU$xQ9ASH3dFq3dwU2oiz5MRU0+3/TCI+PGc2toOMU00WI=	\N	t	jorge			jorgeantonioramirezricardo@gmail.com	t	t	2025-09-21 22:15:28.089663+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	authtoken	token
8	authtoken	tokenproxy
9	tienda	brand
10	tienda	category
11	tienda	servicio
12	tienda	categoriaimagen
13	tienda	product
14	tienda	productimage
15	tienda	servicioimagen
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-09-21 22:12:16.125482+00
2	auth	0001_initial	2025-09-21 22:12:19.041882+00
3	admin	0001_initial	2025-09-21 22:12:19.849204+00
4	admin	0002_logentry_remove_auto_add	2025-09-21 22:12:19.946374+00
5	admin	0003_logentry_add_action_flag_choices	2025-09-21 22:12:20.210393+00
6	contenttypes	0002_remove_content_type_name	2025-09-21 22:12:20.779155+00
7	auth	0002_alter_permission_name_max_length	2025-09-21 22:12:21.136853+00
8	auth	0003_alter_user_email_max_length	2025-09-21 22:12:21.565088+00
9	auth	0004_alter_user_username_opts	2025-09-21 22:12:21.777868+00
10	auth	0005_alter_user_last_login_null	2025-09-21 22:12:22.347728+00
11	auth	0006_require_contenttypes_0002	2025-09-21 22:12:22.524326+00
12	auth	0007_alter_validators_add_error_messages	2025-09-21 22:12:22.796988+00
13	auth	0008_alter_user_username_max_length	2025-09-21 22:12:23.256754+00
14	auth	0009_alter_user_last_name_max_length	2025-09-21 22:12:23.616973+00
15	auth	0010_alter_group_name_max_length	2025-09-21 22:12:23.988588+00
16	auth	0011_update_proxy_permissions	2025-09-21 22:12:24.168497+00
17	auth	0012_alter_user_first_name_max_length	2025-09-21 22:12:24.645104+00
18	authtoken	0001_initial	2025-09-21 22:12:25.288961+00
19	authtoken	0002_auto_20160226_1747	2025-09-21 22:12:25.393978+00
20	authtoken	0003_tokenproxy	2025-09-21 22:12:25.704273+00
21	authtoken	0004_alter_tokenproxy_options	2025-09-21 22:12:26.035438+00
22	sessions	0001_initial	2025-09-21 22:12:26.962477+00
23	tienda	0001_initial	2025-09-21 22:12:29.418285+00
24	tienda	0002_alter_product_brand	2025-09-21 22:12:29.517018+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: tienda_brand; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.tienda_brand (id, name, logo) FROM stdin;
1	Nike	brands/logos/nike.jpeg
2	Adidas	brands/logos/adidas-logo-adidas-icon-free-free-vector.jpg
5	Calvin Klein	brands/logos/ck.jpg
8	¡Phone	brands/logos/iphone-logo-17.png
10	PHILIPS	brands/logos/Philips-Logotipo-1938-1968.jpg
12	Reebock	brands/logos/Reebok-Logo-1977.png
14	SONY	brands/logos/sony.jpg
16	UNDER ARMOUR	brands/logos/under_armour.jpeg
17	ZTE	brands/logos/zte.jpg
18	TOSHIBA	brands/logos/toshiba.jpg
29	PUMA	brands/logos/puma-logo-1200x630.jpg
\.


--
-- Data for Name: tienda_categoriaimagen; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.tienda_categoriaimagen (id, image, "order", category_id) FROM stdin;
\.


--
-- Data for Name: tienda_category; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.tienda_category (id, name, description, image) FROM stdin;
2	Electronica	Laptop, phones, pantallas, piezas y mas	categorias/electronica.jpg
3	Belleza	Articulos de maquillaje, cremas ,perfumes tintes y mucho mas	categorias/bellesa.jpg
4	Vestuario	Camisas, pantalones de vestir, ropa interior, playeras y mas	categorias/people-2557483_1280.jpg
5	Hogar	Encuentra aquí todos los artículos que facilitaran tu vida en tu casa. Productos de decoración ,aseo ,útiles de cocina y mas	categorias/architecture-4470568_1280.jpg
\.


--
-- Data for Name: tienda_product; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.tienda_product (id, title, description, origin, original_price, discount, price, stock, featured, category_deal, created_at, updated_at, brand_id, category_id) FROM stdin;
2	Laptop	Marca: Toshiba Procesador: i7 de 8va ....	USA	700.00	10	630.00	6	t	t	2025-09-28 20:32:39.057311+00	2025-09-28 20:32:39.057321+00	18	2
3	Tenis	Gama media	USA	78.00	0	78.00	2	f	f	2025-09-28 20:33:57.132756+00	2025-09-28 20:33:57.132771+00	12	4
4	Tenis	Marca: Nike ,Tallas(UK): 45, 43, 42	USA	45.00	5	42.75	2	f	f	2025-09-28 20:35:35.808752+00	2025-09-28 20:35:35.808761+00	1	4
5	Playeras	Manga larga y manga corta	USA	67.00	2	65.66	90	t	f	2025-09-28 20:38:53.1172+00	2025-09-28 20:38:53.11721+00	29	4
6	Phone	Phone 13 pro max	USA	8000.00	2	7840.00	4	f	f	2025-09-28 20:46:47.40616+00	2025-09-28 20:46:47.40617+00	8	2
\.


--
-- Data for Name: tienda_productimage; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.tienda_productimage (id, image, "order", product_id) FROM stdin;
2	products/images/laptop_tosh.jpeg	1	2
3	products/images/laptop_tosh1.jpeg	2	2
4	products/images/laptop_tosh2.jpeg	3	2
5	products/images/tenis.webp	1	3
6	products/images/tenis1.jpeg	2	3
7	products/images/tenis2.jpeg	3	3
8	products/images/tenisnike.webp	1	4
9	products/images/tenisnike3.webp	2	4
10	products/images/playerapuma.webp	1	5
11	products/images/playerapuma1.webp	2	5
12	products/images/playerapuma2.webp	3	5
13	products/images/phone.jpeg	1	6
14	products/images/phone1.jpeg	2	6
\.


--
-- Data for Name: tienda_servicio; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.tienda_servicio (id, "nombreServicio", "precioOriginal", descuento, precio, descripcion, caracteristicas, created_at, updated_at) FROM stdin;
50	Domicilio	45.00	0	45.00	Hasta la puerta de tu casa en todo San Juan del Rio	{}	2025-09-28 19:54:53.88378+00	2025-09-28 19:54:53.883791+00
51	Alquiler cine en casa	450.00	0	450.00	Incluye maquina de palomitas, equipo potente de audio, dos colchones inflables, pantalla con prollector de alta calidad ideal para actividades de todo tipo	{}	2025-09-28 19:57:13.952508+00	2025-09-28 19:57:42.991929+00
\.


--
-- Data for Name: tienda_servicioimagen; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.tienda_servicioimagen (id, image, "order", service_id) FROM stdin;
30	servicios/None/servicio_domicilio.png	1	50
31	servicios/None/cine_en_casa.png	1	51
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 60, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 15, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 24, true);


--
-- Name: tienda_brand_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.tienda_brand_id_seq', 33, true);


--
-- Name: tienda_categoriaimagen_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.tienda_categoriaimagen_id_seq', 1, false);


--
-- Name: tienda_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.tienda_category_id_seq', 5, true);


--
-- Name: tienda_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.tienda_product_id_seq', 6, true);


--
-- Name: tienda_productimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.tienda_productimage_id_seq', 14, true);


--
-- Name: tienda_servicio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.tienda_servicio_id_seq', 51, true);


--
-- Name: tienda_servicioimagen_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.tienda_servicioimagen_id_seq', 31, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: tienda_brand tienda_brand_name_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tienda_brand
    ADD CONSTRAINT tienda_brand_name_key UNIQUE (name);


--
-- Name: tienda_brand tienda_brand_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tienda_brand
    ADD CONSTRAINT tienda_brand_pkey PRIMARY KEY (id);


--
-- Name: tienda_categoriaimagen tienda_categoriaimagen_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tienda_categoriaimagen
    ADD CONSTRAINT tienda_categoriaimagen_pkey PRIMARY KEY (id);


--
-- Name: tienda_category tienda_category_name_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tienda_category
    ADD CONSTRAINT tienda_category_name_key UNIQUE (name);


--
-- Name: tienda_category tienda_category_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tienda_category
    ADD CONSTRAINT tienda_category_pkey PRIMARY KEY (id);


--
-- Name: tienda_product tienda_product_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tienda_product
    ADD CONSTRAINT tienda_product_pkey PRIMARY KEY (id);


--
-- Name: tienda_productimage tienda_productimage_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tienda_productimage
    ADD CONSTRAINT tienda_productimage_pkey PRIMARY KEY (id);


--
-- Name: tienda_servicio tienda_servicio_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tienda_servicio
    ADD CONSTRAINT tienda_servicio_pkey PRIMARY KEY (id);


--
-- Name: tienda_servicioimagen tienda_servicioimagen_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tienda_servicioimagen
    ADD CONSTRAINT tienda_servicioimagen_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: tienda_brand_name_f3643dc4_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX tienda_brand_name_f3643dc4_like ON public.tienda_brand USING btree (name varchar_pattern_ops);


--
-- Name: tienda_categoriaimagen_category_id_ab863296; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX tienda_categoriaimagen_category_id_ab863296 ON public.tienda_categoriaimagen USING btree (category_id);


--
-- Name: tienda_category_name_e4d1640a_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX tienda_category_name_e4d1640a_like ON public.tienda_category USING btree (name varchar_pattern_ops);


--
-- Name: tienda_product_brand_id_36bbae26; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX tienda_product_brand_id_36bbae26 ON public.tienda_product USING btree (brand_id);


--
-- Name: tienda_product_category_id_2ea31a5d; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX tienda_product_category_id_2ea31a5d ON public.tienda_product USING btree (category_id);


--
-- Name: tienda_productimage_product_id_e01bbcd4; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX tienda_productimage_product_id_e01bbcd4 ON public.tienda_productimage USING btree (product_id);


--
-- Name: tienda_servicioimagen_service_id_732c727b; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX tienda_servicioimagen_service_id_732c727b ON public.tienda_servicioimagen USING btree (service_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_categoriaimagen tienda_categoriaimag_category_id_ab863296_fk_tienda_ca; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tienda_categoriaimagen
    ADD CONSTRAINT tienda_categoriaimag_category_id_ab863296_fk_tienda_ca FOREIGN KEY (category_id) REFERENCES public.tienda_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_product tienda_product_brand_id_36bbae26_fk_tienda_brand_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tienda_product
    ADD CONSTRAINT tienda_product_brand_id_36bbae26_fk_tienda_brand_id FOREIGN KEY (brand_id) REFERENCES public.tienda_brand(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_product tienda_product_category_id_2ea31a5d_fk_tienda_category_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tienda_product
    ADD CONSTRAINT tienda_product_category_id_2ea31a5d_fk_tienda_category_id FOREIGN KEY (category_id) REFERENCES public.tienda_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_productimage tienda_productimage_product_id_e01bbcd4_fk_tienda_product_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tienda_productimage
    ADD CONSTRAINT tienda_productimage_product_id_e01bbcd4_fk_tienda_product_id FOREIGN KEY (product_id) REFERENCES public.tienda_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_servicioimagen tienda_servicioimagen_service_id_732c727b_fk_tienda_servicio_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tienda_servicioimagen
    ADD CONSTRAINT tienda_servicioimagen_service_id_732c727b_fk_tienda_servicio_id FOREIGN KEY (service_id) REFERENCES public.tienda_servicio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: cloud_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO neon_superuser WITH GRANT OPTION;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: cloud_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT ALL ON TABLES TO neon_superuser WITH GRANT OPTION;


--
-- PostgreSQL database dump complete
--

