# Generated by Django 5.2.1 on 2025-06-27 17:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la marca')),
                ('logo', models.ImageField(upload_to='marcas/logos/', verbose_name='Logo de la marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('origin', models.CharField(choices=[('USA', 'Estados Unidos'), ('JPN', 'Japón'), ('GER', 'Alemania'), ('KOR', 'Corea del Sur'), ('CHN', 'China')], default='USA', max_length=3, verbose_name='Origen')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio original')),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento (%)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio con descuento')),
                ('availability', models.PositiveIntegerField(default=0, verbose_name='Disponibilidad')),
                ('destacado', models.BooleanField(default=False, verbose_name='Producto destacado')),
                ('categoria_oferta', models.BooleanField(default=False, verbose_name='En oferta de categoría')),
                ('categoria', models.CharField(choices=[('Electrónica', 'Electrónica'), ('Fotografía', 'Fotografía'), ('Video', 'Video'), ('Audio', 'Audio'), ('Informática', 'Informática')], default='Electrónica', max_length=50, verbose_name='Categoría')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tienda.marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-destacado', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/imagenes/', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de productos',
                'ordering': ['orden'],
            },
        ),
    ]
