# Generated by Django 5.2.1 on 2025-07-02 15:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_producto_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Brand name')),
                ('logo', models.ImageField(upload_to='brands/logos/', verbose_name='Brand logo')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='productoimagen',
            name='producto',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('origin', models.CharField(choices=[('USA', 'United States'), ('JPN', 'Japan'), ('GER', 'Germany'), ('KOR', 'South Korea'), ('CHN', 'China')], default='USA', max_length=3, verbose_name='Origin')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Original price')),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount (%)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Discounted price')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock quantity')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured product')),
                ('category_deal', models.BooleanField(default=False, verbose_name='Category deal')),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Photography', 'Photography'), ('Video', 'Video'), ('Audio', 'Audio'), ('Computing', 'Computing')], default='Electronics', max_length=50, verbose_name='Category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tienda.brand')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tienda.product')),
            ],
            options={
                'verbose_name': 'Product image',
                'verbose_name_plural': 'Product images',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='ProductoImagen',
        ),
    ]
