# Generated by Django 5.2.1 on 2025-07-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_brand_remove_producto_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Ropa', 'Ropa'), ('Hogar', 'Hogar'), ('Deportes', 'Deportes'), ('OtrOs', 'OtrOs')], default='Electronics', max_length=50, verbose_name='Category'),
        ),
    ]
